server:
  port: 9004

spring:
  application:
    name: auth-service
  data:
    mongodb:
      uri: mongodb+srv://root:1234@sop.q0pttqg.mongodb.net/test
      database: CARENT
jwt:
  secret: DAKjfg1ndlmkngl6jeEOlgkdslmsd;gl78LGlcdkni27NKmksdhfPcdlgfr7vdkhgrpOgmflbfY
  expiration: 86400
